apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  selector:    
    app: kibana
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  type: LoadBalancer